### ISSUE TITLE
Providing an option to  run lessc from Emacs

### ISSUE THREAD

**Issue by TatriX** [purcell/skewer-less#1]
> I may consider providing an option to instead run lessc from Emacs, then send the output via skewer-css. Let me know if you want this.

I want this ;)

**Comment by TatriX** [comment]
Awesome! Thank you.

**Comment by purcell** [comment]
I've only provided `C-c C-k`, because I think it wouldn't work well to send smaller chunks of the file, since they will usually depend on included files or variable definitions elsewhere.
